### ISSUE TITLE
Raspberry power sensor and apt update sensor missing or incomplete in MQTT messages

### ISSUE THREAD

**Issue by JaccovL** [hjelev/rpi-mqtt-monitor#213]
Since the latest update the mqtt message apt_update_availability ( = online) is missing. Therefore the Home Assistant sensor is showing as "unavailable" when using auto discovery. When pushing this message manually, the sensor becomes available again.

The sensor rpi_power_status is not auto discovered anymore while the messages in the MQTT broker is looking just ok.
When looking a bit further, it looks like unit_of_measurement, state_class and availability topic definitions are missing in the discovery section.

If you need me to do more debugging, please let me know how.

Thank you,
Jacco

**Comment by hjelev** [comment]
Thanks for reporting, I have added some state_classes that turns out to be wrong.
I have reverted the change, please test version 1.1.11

Regards,

**Comment by JaccovL** [comment]
Thanks! I'll report back today or tomorrow.

Regards

**Comment by JaccovL** [comment]
Looking good so far. The sensors are back and available again. in HA auto discovery.

Thanks,
Jacco

**Comment by hjelev** [comment]
> [@hjelev](https://github.com/hjelev) I don't know if this belongs here, but:
> 
> The update entity and the corresponding binary sensor entity “disappear” from Home Assistant a few days after starting (e.g. after an update) the RPi-MQTT monitor. They are displayed as not available and no longer provided by the integration. This was already the case with versions prior to 1.1.11.
> 
> They then no longer appear under the topic homeassistant/binary_sensor or homeassistant/update.

what is your version?
The latest version should not have these issues, you can manually update using the -u option if hass updates are broken.

**Comment by hjelev** [comment]
@z-master42  have you restarted the service or the device after the update?
The issues you are reporting are fixed in version 1.2.0
Do you have the same issue on all 3 devices?

**Comment by z-master42** [comment]
Yes, I restarted the service after each update.

At the moment, the entities are only unavailable for one of three devices, but they have never failed at the same time before and when I look at the topics with the MQTT explorer, as I said, the discovery topics under homeassistant/binary_sensor and homeassistant/update are missing for all three devices. The discovery topics for the other sensors can all be found under homeassistant/sensor.

**Comment by z-master42** [comment]
Still the Same with 1.2.1.

**Comment by hjelev** [comment]
@z-master42 have you tried deleting the device from hass mqtt section so its recreated with the next run of the script?

**Comment by z-master42** [comment]
Sorry for the late reply.
I have deleted the topics for all three devices via the MQTT explorer, both the value topics and the discovery topics.

As soon as values are transmitted again from the respective device, the two update entities are still not available for two of the three devices.

I do not know why. I have set up all three devices one after the other and cannot remember having taken any other steps.

**Comment by hjelev** [comment]
the apt_update and other update sensor are not send every time values are send to hass.
They are are send based on update_check_interval. Also apt_update is disabled by default (when installed with auto installer).
These 2 are send when the script is started and then each 1h if you are using default configuration.

**Comment by z-master42** [comment]
Ahh, thank you for this enlightening information.
